USE [master]
GO

/****** Object:  Database [OPS]    Script Date: 08/02/2021 16:10:28 ******/
CREATE DATABASE [OPS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OPS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OPS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OPS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OPS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OPS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OPS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OPS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OPS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OPS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OPS] SET ARITHABORT OFF 
GO

ALTER DATABASE [OPS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OPS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OPS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OPS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OPS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OPS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OPS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OPS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OPS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OPS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OPS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OPS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OPS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OPS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OPS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OPS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OPS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OPS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OPS] SET  MULTI_USER 
GO

ALTER DATABASE [OPS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OPS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OPS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OPS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OPS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OPS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OPS] SET  READ_WRITE 
GO

